[package]
name = "sui-squad-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
sui-squad-core = { path = "../sui-squad-core" }
teloxide = { version = "0.12" }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
tracing-subscriber = "0.3"
anyhow = "1.0" 